export  const routes =[
    {
        path:'/register',
        name:'Register',
        component:r=>require(['../views/Register.vue'],r)
    },
    {
        path:'/detail',
        name:'Detail',
        component:r=>require(['../views/Detail.vue'],r)
    },
    {
        path:'/pay',
        name:'Pay',
        component:r=>require(['../views/Pay.vue'],r)
    },
    {
        path:'/forgot',
        name:'Forgot',
        component:r=>require(['../views/Forgot.vue'],r)
    },
    {
        path:'/like',
        name:'Like',
        component:r=>require(['../views/Like.vue'],r)
    },
    {
        path:'/secure',
        name:'Secure',
        component:r=>require(['../views/Secure.vue'],r)
    },
    {
        path:'/accounts',
        name:'Accounts',
        component:r=>require(['../views/Accounts.vue'],r)
    },
    {
        path:'/address:aid?',
        name:'Address',
        component:r=>require(['../views/Address.vue'],r)
    },
    {
        path:"/myaddress",
        name:'MyAddress',
        component:r=>require(['../views/MyAddress.vue'],r)
    },
    {
        path:'/login',
        name:'Login',
        component:r=>require(['../views/Login.vue'],r)
    },
    {
        path:'/main',
        name:'Main',
        component:r=>require(['../views/Main.vue'],r),
        children:[
            {
                path:'menu',
                name:'Menu',
                component:r=>require(['../views/Inviews/Menu.vue'],r)
            },
            {
                path:'my',
                name:'My',
                component:r=>require(['../views/Inviews/My.vue'],r)
            },
            {
                path:'order',
                name:'Order',
                component:r=>require(['../views/Inviews/Order.vue'],r)
            },
            {
                path:'shopcart',
                name:'Shopcart',
                component:r=>require(['../views/Inviews/Shopcart.vue'],r)
            },
        ]
    },
    {
        path:'*',
        redirect:{
            name:"Login"
        }
    }

]